const lightMode = {
  colors: {
    font: {
      primary: '#333333',
      info: '#999999',
      tooltip: '#ffffff',
      favorite: '#f5bc00',
      success: '',
      processing: '',
      error: '',
      highlight: '',
      hover: '',
      normal: '',
    },
    background: {
      primary: '#ffffff',
      info: '#FEF9EE',
      darkish: '#f7f7f7',
      highlight: '#ffffff',
      normal: '#1e2126',
      scrollTrack: '#a3a3a3',
      scrollThumb: '#d4d4d4',
      tooltip: '#000000',
      hover: '#FDF7EC',
      favorite: '#f5bc00',
      success: '',
      processing: '',
      error: '',
    },
    border: {
      primary: '#e6e6e6',
      info: '',
      success: '',
      processing: '',
      error: '',
      highlight: '',
      hover: '',
      normal: '',
    },
  },
};
export default lightMode;
