// Daily Stats
export const GET_DAILY_STATS_ASYNC = 'GET_DAILY_STATS_ASYNCH';
export const GET_DAILY_STATS = 'GET_DAILY_STATS';

// OrderBook
export const GET_ORDER_BOOK_ASYNC = 'GET_ORDER_BOOK_ASYNCH';
export const GET_ORDER_BOOK = 'GET_ORDER_BOOK';

// CryptoPairs
export const GET_CRYPTO_PAIRS_ASYNC = 'GET_CRYPTO_PAIRS_ASYNCH';
export const GET_CRYPTO_PAIRS = 'GET_CRYPTO_PAIRS';
